CALL_KEY = 'Call'
PID_KEY = 'PID'
TRANSACTION_KEY = 'Transaction'
RESULT_KEY = 'Result'
SALE_STATUS_KEY = 'SaleStatus'
KEY_IMAGE_KEY = 'KeyImage'
PAY_STATUS_KEY = 'PayStatus'
BROADCAST_KEY = 'Broadcast'
APPROVALS_KEY = 'Approvals'
APPROVAL_KEY = 'Approval'

BROADCAST_SALE = 'Sale'
BROADCAST_PAY = 'Pay'
BROADCAST_APPROVAL = 'BroadcastApproval'
BROADCAST_TRANSACTION = 'BroadcastTransaction'
BROADCAST_PAY_REQUEST = 'BroadcastPayRequest'

STATUS_OK = 0
STATUS_APPROVED = 0
STATUS_PROCESSING = 1
STATUS_REJECTED = 2
STATUS_NONE = -1

ERROR_PAYMENT_ID_DOES_NOT_EXISTS = -1
ERROR_PAYMENT_ID_ALREADY_EXISTS = -2
ERROR_EMPTY_PARAMS = -3
ERROR_ACCOUNT_LOCKED = -4
ERROR_BROADCAST_FAILED = -5
ERROR_INVALID_TRANSACTION = -6

REDIS_GENERAL_CHANNEL = 'graft_supernode_general:%s'
REDIS_JOB_RESULT_KEY = REDIS_GENERAL_CHANNEL % 'job_result::%s'
