PID_KEY = 'PID'
TRANSACTION_KEY = 'Transaction'
RESULT_KEY = 'Result'
SALE_STATUS_KEY = 'SaleStatus'
KEY_IMAGE_KEY = 'KeyImage'
PAY_STATUS_KEY = 'PayStatus'
BROADCAST_KEY = 'Broadcast'


STATUS_OK = 0
STATUS_APPROVED = 0
STATUS_PROCESSING = 1
STATUS_REJECTED = 2
STATUS_NONE = -1

ERROR_PAYMENT_ID_DOES_NOT_EXISTS = -1
ERROR_PAYMENT_ID_ALREADY_EXISTS = -2
ERROR_EMPTY_PARAMS = -3
ERROR_ACCOUNT_LOCKED = -4
ERROR_BROADCAST_FAILED = -5
